### ISSUE TITLE
Where can I find your paper?

### ISSUE THREAD

**Issue by LeeBY68** [VITA-Group/Aug-NeRF#1]
Thanks for your wonderful work! It is really interesting !

However, where can I find this paper?

Looking for your reply!

**Comment by reynoldscem** [comment]
https://openaccess.thecvf.com/content/CVPR2022/html/Chen_Aug-NeRF_Training_Stronger_Neural_Radiance_Fields_With_Triple-Level_Physically-Grounded_Augmentations_CVPR_2022_paper.html
