### ISSUE TITLE
GPU Memory Requirement

### ISSUE THREAD

**Issue by Ailon-Island** [VITA-Group/Aug-NeRF#3]
How much memory does training Aug-NeRF require? For my RTX 3070 with 8GB memory, it keeps running out of memory even when I set `--ray_chunk 32` and `--pts_chunk 256`. Shall I give up training Aug-NeRF on my RTX 3070?

**Comment by peihaowang** [comment]
Hi Wei,

Thanks for your interest. In current implementation, neither changing `--ray_chunk` nor `--pts_chunk` would save memory cost. To save memory, we would suggest reduce `--batch_size `. Hope you will find this helpful.

Best,
Peihao

**Comment by Ailon-Island** [comment]
Hello Peihao, I've tried your suggestion with a batch size as small as `1`, but my memory still got exceeded. Perhaps my memory is just not enough. Thanks for your timely support anyway.
